load("../../resources/stereoParams.mat");
% K1 = stereoParams.CameraParameters1.IntrinsicMatrix';
intrinsic_matrix_left = stereoParams.CameraParameters1.Intrinsics.K;
intrinsic_matrix_right = stereoParams.CameraParameters2.Intrinsics.K;
distortion_left = [stereoParams.CameraParameters1.RadialDistortion, ...
                   stereoParams.CameraParameters1.TangentialDistortion];
distortion_right = [stereoParams.CameraParameters2.RadialDistortion, ...
                    stereoParams.CameraParameters2.TangentialDistortion];
rotation_matrix = stereoParams.PoseCamera2.R;
translation = stereoParams.PoseCamera2.Translation;
image_size = stereoParams.CameraParameters1.ImageSize;
save("../../resources/essential_parameters.mat",...
     "intrinsic_matrix_left", ...
     "intrinsic_matrix_right", ... 
     "distortion_left", ...
     "distortion_right", ...
     "rotation_matrix", ...
     "translation", ...
     "image_size");