focal_length = cameraParams.FocalLength;
principal_point = cameraParams.PrincipalPoint;
K = cameraParams.Intrinsics.K;
distortion = [cameraParams.RadialDistortion, ...
              cameraParams.TangentialDistortion];
save("../../resources/essential_parameters_single.mat",...
     "focal_length", ...
     "principal_point", ...
     "K", ...
     "distortion");